// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.6_@types+node@20.5.1_eslint@8.57.0_prettier@3.2.5_react-dom@18.2_llan2tm5b242q332o6olqi2nui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/site/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.6_@types+node@20.5.1_eslint@8.57.0_prettier@3.2.5_react-dom@18.2_llan2tm5b242q332o6olqi2nui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/site/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/site/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/qiangshao/shine/github/qqxs/pnpm-workspace/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.6_@types+node@20.5.1_eslint@8.57.0_prettier@3.2.5_react-dom@18.2_llan2tm5b242q332o6olqi2nui/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
