// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/qiangshao/shine/github/qqxs/pnpm-workspace/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.6_@types+node@20.5.1_eslint@8.57.0_prettier@3.2.5_react-dom@18.2_llan2tm5b242q332o6olqi2nui/node_modules/dumi/theme-default/builtins/Tree/index.js';
